#Common Configs for Advanced Clover
[mode_settings]
#Working mode of the magic clover. Avaliable values are
#'whitelist', 'blacklist'.
#Default: 'blacklist'
"Working Mode" = "whitelist"
#Items in Magic Clover blacklist. These items will not be spawned if mod is working on blacklist mode.
#Supports regex.
blacklist_items = [
	"minecraft:air",
	"minecraft:bedrock",
	"minecraft:barrier",
	"minecraft:light",
	"minecraft:.*command_block.*",
	"minecraft:jigsaw",
	"minecraft:structure_block",
	"minecraft:structure_void",
	"minecraft:debug_stick",
	"advanced_clover:..*_leaf_clover",
	".*debug.*",
	"minecraft:map",
	"minecraft:potion",
	"minecraft:tipped_arrow",
	"minecraft:suspicious_stew",
	"minecraft:enchanted_book",
	"minecraft:goat_horn",
	"minecraft:vault",
]
#Items in Magic Clover whitelist. These items will only be spawned if mod is working on whitelist mode.
#Supports regex.
whitelist_items = [
	"minecraft:(?!.*spawn_egg).*(copper|iron|gold|diamond|redstone|lapis|emerald|netherite).*",
	"minecraft:(?!.*spawn_egg).*(dirt|wool|glass|grass|seed|bundle|boat|wood|birch|oak|jungle|acacia|mangrove|cherry|cobble|bamboo).*",
	"minecraft:(?!.*spawn_egg).*(diorite|deepslate|granite|tuff|sand|obsidian|prismari|nether|end|purpur).*",
	"minecraft:minecart",
	"minecraft:(?!.*spawn_egg).*(apple|cake|fish|berries|cooked|bread|potato|carrot|dandelion).*",
	"minecraft:.*(undying_tot|armor|_dye)",
	"minecraft:heart_of_the_sea",
	"bakeries:.*(powder|flour|toast|yolk|bread|dough).*",
	"bsf3lite:((smooth|duck|compacted|cherry_blossom|stone|ice|iron|obsidian|explosive|spectral)_snowball(_set)?|((powerful|freezing)_)?snowball_(cannon|machine_gun|shotgun|rifle)|.*(tank|clamp|glove|popsicle)|basin|snowman_in_hand|sculk_snowball_launcher|repulsive_field_generator|ice_skates|snow_fall_boots|vodka)",
	"modulargolems:(?!.*spawn_egg).*golem.*",
	"advanced_clover:.*_leaf_clover",
	"harvestheritage:.*_stand_block",
	"harvestheritage:grass_shear",
	"harvestheritage:(magnifying_glass|zzzz)",
	"mekanism:.*(dust_|nugget_|block_|raw_|ingot_|hazmat_|circuit).*",
	"mekanism:.*(_scrap|_installer)",
	"mekanism:(pellet|enriched|alloy).*",
	"meka.*:.*(_helmet|_chestplate|_leggings|_boots|_shield|_sword|_paxel|_axe|_hoe|_shovel)",
	"meka.*:.*reactor.*",
	"mekmm:.*factory.*",
	"super_lead:super_lead",
	"eclipticseasons:pinwheel.*",
	"eclipticseasons:.*(chimes|wand|hygrometer)",
	"shadowsandpetals:.*",
	"programmable_magic:.*alloy_wand",
	"programmable_magic:.*plugin.*(supply|storage|release|color).*",
	"letter_signal_phone:.*phone.*",
	"letter_signal_phone:.*telegram.*",
	"letter_signal_phone:stamp_pack",
	"nestle:(nestle_lead|nestle_bound|nestle)",
	"shakenstir:shaker",
	"shakenstir:(ice|lemon|tequ).*",
	"shakenstir:.*tea.*",
	"shakenstir:(vodka|rum|whisky|gin|brandy)",
	"shakenstir:.*glassware",
	"terraria_boulders:boulder_glove",
	"beecrasy:(?!.*spawn_egg).*(comb|bee_nest).*",
	"beecrasy:(skep|apite|honey_drop|beeswax|pheromone)",
	"displaydoll:.*",
	"ashihara:(?!.*spawn_egg).*(daifuku|rice|dango|pot|potato|otsuchi|mochi|tofu|soy_bean|cotton|cucumber|tomato|sapling|sushi|reed|candle).*",
	"ashihara:(?!.*spawn_egg).*(cherry|maple|red|cypress|lantern|white|water|lamp|stick|tatami).*",
	"ashihara:(?!.*spawn_egg).*(sakura|bamboo|powder|flour|bucket|dirt|soil|tamago|shatter|salt).*",
	"superpipeslide:.*(_anchor|guide|projector)",
	"minecartrevolution:*(_chest|anvil|_plate|campfire|cactus|beacon|portal|obsidian|amethyst|piston|_rail)",
	"netmusic:music_cd|music_player|cd_burner|computer",
	"powertool:.*(marting_car|clap|cosmetic).*",
	"kaleidoscope:.*(lights|painting|board|grape|bucket|wine|brandy|champag|bottle|bride|dry_white).*",
	"wenyan_progr.*:.*_ink",
	"wenyan_addon:.*block",
	"living_unvanished:.*(skull|suspicious|bucket|eather)",
	"dungeon_infinity:.*(key_of|block).*",
	"sip_moment:.*",
	"caupona:.*(loaf|aspic|spice_jar|walnut|fig|tesse|snail|wolfberries|gravy|tuff|column|frying_pan|mud_|skimmer|scraps|asses|lead|leaves|silphium|charcoal|asafoe|litharge|brick).*",
	"convivium:.*(camellia|powder|glass|_juice|cage_wheel|basin).*",
	"a_better_foods:.*",
	"better_rod:.*(bait|hook|line)",
	"neo_mystias_izakaya.*",
	"beyond:loot_bag",
	"obeliskdep.*:.*",
	"yuushya:(?!.*(item|encyclopedia|shimmering_pearl|lasting_wood|sprouting_|floating_|sparkling_|alert).*)",
	"touhou_little_maid:.*(chair|garage_kit|backpack|power_point|gohei|chess|bed|bauble|bookshelf|keyboard)",
	"craton:.*",
	"furnitureplan:.*",
	"dynamictrees:.*",
	"ether_craft:(?!.*wrench).*",
	".*_icaruswings:(?:.*(?:_feather|_gem|herb|_template|beeswax|glass_jar|flax|string|linen|wheat|spear|disc_|melon|honey_cake|elysian|fleece|grains).*|(?:mead|anemone|amphora))",
	"industrybase:.*",
	"gensokyooton.*:.*(maple|zelkova|sakura|redwood|ginkgo|wasabi|jade|mushroom).*",
	"kilagraph.*:.*",
	"maid_bakeries:.*list",
	"maid_storage:.*(calculator|card|guide).*",
	"ae2:.*(paint_ball|fluix|certus|_cable).*",
	"channel:.*",
	"guide_me_to:.*",
	"lanfasie.*:.*(sword|praiser|provoking|).*",
	"neoecoae:.*",
	"net_music_can_play_bili:.*",
	"ultramarine:(?!.*(wooden_mallet|axe|shovel).*).*",
	"minethespire:.*(lizard_|mango|pear|strawberry|burning_blood|of_the_snake|cracked_core|dark_shuriken|bouncing_flask|spirit|_orb|heavy_blade|pain_strike|chemical_x).*",
	"vw50:.*",
	"ourthoughtsareone:projection_core",
	"cc_ms:.*",
	"let_me_see.*:item_data_exporter",
	"netherlink:.*",
	"transmutatoria:(?:(?:nigredo_|albedo_|citrinitas_)?(?:eclipsium|lunargent|astrotite|abyssion|animercury|necroplumb|sanguibronze|venotite|ossantimony|fulgurzinc|chronoplatinum|pandemonium)|(?:salic|mercurial|sulfuric)_matrix)",
	"girlfriends:.*",
	"woodenanvil:.*",
	"cc_mb:.*",
	"ccw:.*(_sugar|milk_gelatin|smithing_wafer|sweet_melon_slice|energy_carrot|blessed_steak)",
	"delicacyworld:.*(raw|cooked|sauce|salt|recipe|money|remote_control|table).*",
	"xkdeco:.*",
	"mtr:.*station_name.*",
	"olruL.*",
	"stoneworks:.*",
	"simple_path_finder:(navigation|locator)",
	"skyward.*:.*",
	"trading_table:.*",
	"crockpot:.*(eggplant|corn|seeds|garlic|onion|pepper|tomato|smithing_template|cooked_egg|frog|hoglin|bottle|syrup|goat_horn|).*",
	"astral_craft:board_spectator"


	
]
#Chance to spawn mob when using clover. Range 0 ~ 1000, default value 10(1%).
# Default: 10
# Range: 0 ~ 1000
mobSpawnChance = 10
