This file is used to mark that the mod is in the Teacon state.
The mod would run in low performance mode to satisfy Teacon requirements.
It does not contain any other configuration content.
Please do not delete it.
