_version = 4
enableDistantGeneration = true

[server]
  [common.logging]
    [common.logging.warning]
			showSlowWorldGenSettingWarnings = false
			showUpdateQueueOverloadedChatWarning = false
			showLowMemoryWarningOnStartup = true
			showReplayWarningOnStartup = true
			showModCompatibilityWarningsOnStartup = true
			showHighVanillaRenderDistanceWarning = false
			showPoolInsufficientMemoryWarning = true
			logGarbageCollectorWarning = true
			showGarbageCollectorWarning = false
	
	[common.worldGenerator]
		generationCenterChunkZ = 128
		generationCenterChunkX = 128
		generationMaxChunkRadius = 128

[client]
	showDhOptionsButtonInMinecraftUi = true

		[client.advanced.autoUpdater]
			enableAutoUpdater = false

		[client.advanced.multiplayer]
			serverFolderNameMode = "NAME_ONLY"

		[client.advanced.graphics]

			[client.advanced.graphics.quality]
				lodChunkRenderDistanceRadius = 144

			[client.advanced.graphics.experimental]

				renderingEngine = "OPEN_GL"