#是否开启摄像头偏移
enableCameraOffset = true
#是否使用双击疾跑闪避(防止误操作)
enableDoubleClickDodge = true

[key_hints]
#是否显示按键教程
enableKeyHints = false
#移动时最低透明度
#范围: 0.0 - 1.0
#默认值: 0.4
# Default: 0.4
# Range: 0.0 ~ 1.0
minAlphaWhenMoving = 0.4
#最大透明度
#范围: 0.0 - 1.0
#默认值: 1.0
# Default: 1.0
# Range: 0.0 ~ 1.0
maxAlpha = 1.0
#内容变化后高亮持续时间（单位：tick）
#默认值: 80 (4秒)
# Default: 80
# Range: > 0
freshDuration = 80
#静止多久后淡入（单位：tick）
#默认值: 100 (5秒)
# Default: 100
# Range: > 0
idleDelay = 100
#视为移动的速度阈值（平方值）
#默认值: 0.005
# Default: 0.005
# Range: 0.0 ~ 1.7976931348623157E308
moveThresholdSqr = 0.005
#淡入速度（值越小越慢）
#范围: 0 - 1.0
#默认值: 0.08
# Default: 0.01
# Range: 0.0 ~ 1.0
fadeInSpeed = 0.01
#淡出速度（值越小越慢）
#范围: 0 - 1.0
#默认值: 0.18
# Default: 0.18
# Range: 0.0 ~ 1.0
fadeOutSpeed = 0.18

[function_switches]
#是否开启趴下
enableProne = true
#是否开启滑铲
enableSlide = true
#是否开启受身准备
enableBreakFallReady = true
#是否开启受身
enableBreakFall = true
#是否开启闪避
enableDodge = true
#是否开启爬墙
enableWallClimb = true
#是否开启滑墙
enableWallSlide = true
#是否开启墙跑
enableWallRun = true
#是否开启挂墙
enableWallHang = true
#是否开启蓄力跳
enablePowerJump = true
#是否开启蹬墙跳
enableWallKick = true
#是否开启翻越
enableVaultUp = true
#是否开启翻入
enableVaultIn = true
#是否开启水上漂(需要助推器)
enableWaterRun = true
#是否开启水中推进(海豚跳)
enableWaterPush = true
#是否开启缓降(需要助推器)
enableFallSlow = true
#是否开启空中二段跳(需要助推器)
enableAirJump = true
