# Dispatch chunks in third-party approaches.
# When syncing chunks, the server sends a small diff instead of full data, reducing network bandwidth usage.
[chunk_cdn]
	# Cache L1's max size
	cache_l1_max = 1024
