#When enabled, NeoForge will show any warnings that occurred during loading.
showLoadWarnings = true
#A config option mainly for developers. Logs out configuration values that do not have translations when running a client in a development environment.
logUntranslatedConfigurationWarnings = false
#Configures how many bits are used for the depth buffer when stenciling has been enabled by a mod. Set to true for 24+8 bits and to false for 32+8 bits. Setting to true will slightly reduce VRAM usage, but risks introducing visual artifacts.
reducedDepthStencilFormat = false
#Enable the enhanced block model lighting pipeline - fixes the lighting of custom models, as well as many vanilla bugs.
enhancedLighting = true
#When enabled, AO will be handled per BlockModelPart instead of using the first part's AO setting
handleAmbientOcclusionPerPart = true
#When enabled, all usage of Blaze3D will be validated against allowed usage
enableB3DValidationLayer = false
#A config option mainly for developers. Logs out modded item tags that do not have translations when running on integrated server. Format desired is tag.item.<namespace>.<path> for the translation key. Defaults to SILENCED.
#Allowed Values: SILENCED, DEV_SHORT, DEV_VERBOSE, PROD_SHORT, PROD_VERBOSE
logUntranslatedItemTagWarnings = "SILENCED"
#When enabled, modded splashes will not be loaded if the vanilla splash text is modified.
skipModdedSplashesIfVanillaModified = true
